# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# cmecloud reset connections from github, use baseimage with gcc11 and maven installed. 
FROM myeyre/gluten:bclinux-8-vcpkg-build-depends

#RUN git clone --depth=1 -b branch-1.4 https://github.com/apache/incubator-gluten /opt/gluten
RUN git clone --depth=1 -b branch-1.4 https://github.com/myeyre/incubator-gluten /opt/gluten

RUN cd /opt/gluten && bash ./dev/vcpkg/setup-build-depends.sh

# An actual path used for vcpkg cache.
RUN mkdir -p /var/cache/vcpkg

# Set vcpkg cache path.
ENV VCPKG_BINARY_SOURCES=clear;files,/var/cache/vcpkg,readwrite

# Build arrow, then install the native libs to system paths and jar package to .m2/ directory.
RUN if [ "$(uname -m)" = "aarch64" ]; then \
        export CPU_TARGET="aarch64"; \
        export VCPKG_FORCE_SYSTEM_BINARIES=1; \
    fi && \
    cd /opt/gluten && source /opt/rh/gcc-toolset-11/enable && \
    bash ./dev/builddeps-veloxbe.sh --enable_vcpkg=ON --build_tests=ON --enable_s3=ON --enable_gcs=ON \
                                    --enable_hdfs=ON --enable_abfs=ON  build_arrow && \
    rm -rf /opt/gluten
