# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#FROM centos:8
#FROM bc-v8.2:8.2.2107
FROM myeyre/bc-v8.2:8.2.2107

#RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-* || true
#RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-* || true
RUN sed -i 's/mirrors.bclinux.org/mirrors.cmecloud.cn/g; s/8.2/8/g; s/\[PowerTools]/[powertools]/g' /etc/yum.repos.d/*.repo

# masq as centos
#RUN echo -e 'NAME="CentOS Linux"\nVERSION="8"\nID="centos"\nID_LIKE="rhel fedora"\nVERSION_ID="8"\nPLATFORM_ID="platform:el8"\nPRETTY_NAME="CentOS Linux 8"\nANSI_COLOR="0;31"\nCPE_NAME="cpe:/o:centos:centos:8"\nHOME_URL="https://centos.org/"\nBUG_REPORT_URL="https://bugs.centos.org/"\nCENTOS_MANTISBT_PROJECT="CentOS-8"\nCENTOS_MANTISBT_PROJECT_VERSION="8"' > /etc/os-release
COPY os-release.centos8 /etc/os-release

#RUN yum update -y && yum install -y epel-release sudo dnf && yum install -y ccache
RUN yum install -y https://mirrors.aliyun.com/epel/epel-release-latest-8.noarch.rpm && yum install -y ccache
RUN dnf install -y --setopt=install_weak_deps=False gcc-toolset-11
RUN echo "check_certificate = off" >> ~/.wgetrc

RUN yum install -y java-1.8.0-openjdk-devel patch wget git perl
ENV JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH
RUN wget --no-check-certificate https://archive.apache.org/dist/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.tar.gz && \
    tar -xvf apache-maven-3.8.8-bin.tar.gz && \
    mv apache-maven-3.8.8 /usr/lib/maven
ENV PATH=${PATH}:/usr/lib/maven/bin
COPY settings.xml /root/.m2/

#RUN git clone --depth=1 -b branch-1.4 https://github.com/apache/incubator-gluten /opt/gluten
RUN git clone --depth=1 -b branch-1.4 https://github.com/myeyre/incubator-gluten /opt/gluten

RUN cd /opt/gluten && bash ./dev/vcpkg/setup-build-depends.sh

# An actual path used for vcpkg cache.
RUN mkdir -p /var/cache/vcpkg

# bump curl to new version for --retry-all-errors flag
RUN yum -y install xz && \
    curl -L https://github.com/stunnel/static-curl/releases/download/8.14.1/curl-linux-x86_64-glibc-8.14.1.tar.xz|tar -Jxf - -C /usr/bin curl && \
    echo -e "--retry 10\n--retry-delay 3\n--retry-all-errors\n--insecure" >> ~/.curlrc

# Set vcpkg cache path.
ENV VCPKG_BINARY_SOURCES=clear;files,/var/cache/vcpkg,readwrite

# Build arrow, then install the native libs to system paths and jar package to .m2/ directory.
RUN if [ "$(uname -m)" = "aarch64" ]; then \
        export CPU_TARGET="aarch64"; \
        export VCPKG_FORCE_SYSTEM_BINARIES=1; \
    fi && \
    cd /opt/gluten && source /opt/rh/gcc-toolset-11/enable && \
    bash ./dev/builddeps-veloxbe.sh --enable_vcpkg=ON --build_tests=ON --enable_s3=ON --enable_gcs=ON \
                                    --enable_hdfs=ON --enable_abfs=ON  build_arrow && \
    rm -rf /opt/gluten
